# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-24 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181224_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=128),
        ),
    ]
