# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-25 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20181224_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='web_lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.TextField()),
                ('web_url', models.TextField()),
                ('web_type', models.CharField(max_length=32)),
                ('web_icon', models.ImageField(upload_to='web_icon')),
            ],
            options={
                'db_table': 'web_lists',
            },
        ),
        migrations.AddField(
            model_name='web_list',
            name='web_icon',
            field=models.ImageField(default=111, upload_to='web_icon'),
            preserve_default=False,
        ),
    ]
