# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-25 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20181225_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_lists',
            name='web_info',
            field=models.TextField(default=111),
        ),
        migrations.AlterField(
            model_name='web_lists',
            name='web_icon',
            field=models.ImageField(null=True, upload_to='web_icon'),
        ),
    ]
