# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-25 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20181225_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='默认用户', max_length=128),
        ),
    ]
