# Generated by Django 2.1.4 on 2018-12-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.CharField(max_length=256)),
                ('view_number', models.CharField(max_length=16)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='industry_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.CharField(max_length=256)),
                ('origin', models.CharField(max_length=256)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'industry_information',
            },
        ),
    ]
