# Generated by Django 2.1.4 on 2018-12-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('user_icon', models.ImageField(upload_to='icons')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
